### ISSUE TITLE
Schedule to run on 1st day of month

### ISSUE THREAD

**Issue by bcavileer** [amitree/delayed_job_recurring#25]
How can I schedule to run on

1st day of month at 12:00am UTC?
1st day of week at 12:00am UTC?

If I figure this out I will post my solution here or commit changes if necessary.

Any help is appreciated!

**Comment by afn** [comment]
I believe you can do something like

```ruby
run_every 1.month
run_at Time.now.utc.beginning_of_month
timezone 'UTC'
```

and

```ruby
run_every 1.week
run_at Time.now.utc.beginning_of_week
timezone 'UTC'
```

(You could alternatively specify a string for `run_at` like `run_at '2018-01-01T00:00:00Z'` but that would be gradually less efficient over time, since [this](https://github.com/amitree/delayed_job_recurring/blob/master/lib/delayed/recurring_job.rb#L61-L63) is how the next run time is computed)
